---
apiVersion: v1
kind: Service
metadata:
  name: bungee-ingress
  namespace: minecraft-server
spec:
  type: NodePort
  ports:
  - name: game
    port: 25565
    targetPort: 25565
    nodePort: 32021
    protocol: TCP
  selector:
    deployment: bungee